FROM debian:bullseye-slim
LABEL maintainer="Kristian Larsson <kristian@spritelink.net>"

ARG IMAGE

RUN apt-get update -qy \
 && apt-get install -y --no-install-recommends \
    iproute2 \
    python3-ipy \
    socat \
    qemu-system-x86 \
    qemu-utils \
 && rm -rf /var/lib/apt/lists/*

COPY $IMAGE* /
COPY *.py /

EXPOSE 22 161/udp 830 5000 8291 8728 10000-10099
HEALTHCHECK CMD ["/healthcheck.py"]
ENTRYPOINT ["/launch.py"]
