FROM alpine:latest
LABEL maintainer="Kristian Larsson <kristian@spritelink.net>"

ARG IMAGE

RUN apk add --no-cache \
    iproute2 \
    py3-pip \
    socat \
    qemu-system-x86_64 \
    qemu-img \
 && pip3 install --break-system-packages --no-cache-dir ipy

COPY $IMAGE* /
COPY *.py /

EXPOSE 22 161/udp 830 5000 8291 8728 10000-10099
HEALTHCHECK CMD ["/healthcheck.py"]
ENTRYPOINT ["/launch.py"]
